# Generated by Django 5.1.2 on 2024-10-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mass_Name', models.CharField(max_length=100)),
                ('main_image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
