# Generated by Django 5.0.6 on 2024-10-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0003_alter_newsmodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('main_image', models.ImageField(upload_to='images/')),
                ('venue', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
