# Generated by Django 5.0.6 on 2024-10-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0004_eventmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_video', models.URLField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='massesmodel',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
