# Generated by Django 5.0.6 on 2024-10-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churchapp', '0005_aboutmodel_alter_massesmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquirymodel',
            name='subject',
        ),
        migrations.AddField(
            model_name='enquirymodel',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
